# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-03 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('type', models.CharField(choices=[(b'movie', b'Movie'), (b'serie', b'Serie'), (b'documentary', b'Documentary')], max_length=16)),
                ('themoviedb_url', models.URLField(unique=True)),
                ('magnet_link', models.CharField(max_length=1024, unique=True)),
                ('size', models.CharField(blank=True, default=b'', help_text=b'E.g: 100mb', max_length=16, null=True)),
                ('path', models.CharField(help_text=b'Path where the cine will be downloaded', max_length=254, unique=True)),
            ],
        ),
    ]
